using System.Collections.Generic;

namespace Wino.Controls
{
    public static class ControlConstants
    {
        public static Dictionary<WinoIconGlyph, string> WinoIconFontDictionary = new Dictionary<WinoIconGlyph, string>()
        {
            { WinoIconGlyph.None, "\u0020" },
            { WinoIconGlyph.Archive, "\uE066" },
            { WinoIconGlyph.UnArchive, "\uE06C" },
            { WinoIconGlyph.Reply, "\uF176" },
            { WinoIconGlyph.ReplyAll, "\uF17A" },
            { WinoIconGlyph.Sync, "\uE902" },
            { WinoIconGlyph.Send, "\uEA8E" },
            { WinoIconGlyph.LightEditor, "\uE1F6" },
            { WinoIconGlyph.Delete, "\uEEA6" },
            { WinoIconGlyph.DarkEditor, "\uEE44" },
            { WinoIconGlyph.Draft, "\uF3BE" },
            { WinoIconGlyph.Flag, "\uF40C" },
            { WinoIconGlyph.ClearFlag, "\uF40F" },
            { WinoIconGlyph.Folder, "\uE643" },
            { WinoIconGlyph.Forward, "\uE7AA" },
            { WinoIconGlyph.Inbox, "\uF516" },
            { WinoIconGlyph.MarkRead, "\uF522" },
            { WinoIconGlyph.MarkUnread, "\uF529" },
            { WinoIconGlyph.MultiSelect, "\uE84D" },
            { WinoIconGlyph.Save, "\uEA43" },
            { WinoIconGlyph.CreateFolder, "\uE645" },
            { WinoIconGlyph.Pin, "\uF5FF" },
            { WinoIconGlyph.UnPin, "\uE985" },
            { WinoIconGlyph.Star, "\uF70D" },
            { WinoIconGlyph.Ignore, "\uF5D0" },
            { WinoIconGlyph.Junk, "\uE903" },
            { WinoIconGlyph.Find, "\uEA7D" },
            { WinoIconGlyph.Zoom, "\uEE8E" },
            { WinoIconGlyph.SpecialFolderInbox, "\uF516" },
            { WinoIconGlyph.SpecialFolderStarred, "\uF70D" },
            { WinoIconGlyph.SpecialFolderImportant, "\uE2F4" },
            { WinoIconGlyph.SpecialFolderSent, "\uEA8E" },
            { WinoIconGlyph.SpecialFolderDraft, "\uF3BE" },
            { WinoIconGlyph.SpecialFolderArchive, "\uE066" },
            { WinoIconGlyph.SpecialFolderDeleted, "\uEEA6" },
            { WinoIconGlyph.SpecialFolderJunk, "\uE903" },
            { WinoIconGlyph.SpecialFolderChat, "\uE2E3" },
            { WinoIconGlyph.SpecialFolderCategory, "\uF599" },
            { WinoIconGlyph.SpecialFolderUnread, "\uF529" },
            { WinoIconGlyph.SpecialFolderForums, "\uF5B8" },
            { WinoIconGlyph.SpecialFolderUpdated, "\uF565" },
            { WinoIconGlyph.SpecialFolderPersonal, "\uE25A" },
            { WinoIconGlyph.SpecialFolderPromotions, "\uF7B6" },
            { WinoIconGlyph.SpecialFolderSocial, "\uEEEB" },
            { WinoIconGlyph.SpecialFolderOther, "\uE643" },
            { WinoIconGlyph.SpecialFolderMore, "\uF0F4" },
            { WinoIconGlyph.Microsoft, "\uE900" },
            { WinoIconGlyph.Google, "\uE901" },
            { WinoIconGlyph.NewMail, "\uF107" },
            { WinoIconGlyph.TurnOfNotifications, "\uF11D" },
            { WinoIconGlyph.Rename, "\uF668" },
            { WinoIconGlyph.EmptyFolder, "\uE47E" },
            { WinoIconGlyph.DontSync, "\uF195" },
            { WinoIconGlyph.Move, "\uE7B8" },
            { WinoIconGlyph.Mail, "\uF509" },
            { WinoIconGlyph.More, "\uE824" },
            { WinoIconGlyph.CustomServer, "\uF509" },
        };
    }
}
