<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <Platforms>x86;x64;arm64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsTrimmable>true</IsTrimmable>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" />
    <ProjectReference Include="..\Wino.Core.Domain\Wino.Core.Domain.csproj" />
    <ProjectReference Include="..\Wino.Authentication\Wino.Authentication.csproj" />
  </ItemGroup>
</Project>
