using System.Collections.Generic;

namespace Wino.Core.UWP.Controls
{
    public static class ControlConstants
    {
        public static Dictionary<WinoIconGlyph, string> WinoIconFontDictionary = new Dictionary<WinoIconGlyph, string>()
        {
            { WinoIconGlyph.None, "\u0020" },
            { WinoIconGlyph.Archive, "\uE066" },
            { WinoIconGlyph.UnArchive, "\uE06C" },
            { WinoIconGlyph.Reply, "\uF176" },
            { WinoIconGlyph.ReplyAll, "\uF17A" },
            { WinoIconGlyph.Sync, "\uE895" },
            { WinoIconGlyph.Send, "\uEA8E" },
            { WinoIconGlyph.LightEditor, "\uE1F6" },
            { WinoIconGlyph.Delete, "\uEEA6" },
            { WinoIconGlyph.DarkEditor, "\uEE44" },
            { WinoIconGlyph.Draft, "\uF3BE" },
            { WinoIconGlyph.Flag, "\uF40C" },
            { WinoIconGlyph.ClearFlag, "\uF40F" },
            { WinoIconGlyph.Folder, "\uE643" },
            { WinoIconGlyph.Forward, "\uE7AA" },
            { WinoIconGlyph.Inbox, "\uF516" },
            { WinoIconGlyph.MarkRead, "\uF522" },
            { WinoIconGlyph.MarkUnread, "\uF529" },
            { WinoIconGlyph.MultiSelect, "\uE84D" },
            { WinoIconGlyph.Save, "\uEA43" },
            { WinoIconGlyph.CreateFolder, "\uE645" },
            { WinoIconGlyph.Pin, "\uF5FF" },
            { WinoIconGlyph.UnPin, "\uE985" },
            { WinoIconGlyph.Star, "\uE734" },
            { WinoIconGlyph.Ignore, "\uF5D0" },
            { WinoIconGlyph.Find, "\uEA7D" },
            { WinoIconGlyph.Zoom, "\uEE8E" },
            { WinoIconGlyph.SpecialFolderInbox, "\uF516" },
            { WinoIconGlyph.SpecialFolderStarred, "\uF70D" },
            { WinoIconGlyph.SpecialFolderImportant, "\uE2F4" },
            { WinoIconGlyph.SpecialFolderSent, "\uEA8E" },
            { WinoIconGlyph.SpecialFolderDraft, "\uF3BE" },
            { WinoIconGlyph.SpecialFolderArchive, "\uE066" },
            { WinoIconGlyph.SpecialFolderDeleted, "\uEEA6" },
            { WinoIconGlyph.SpecialFolderJunk, "\uF140" },
            { WinoIconGlyph.SpecialFolderChat, "\uE8BD" },
            { WinoIconGlyph.SpecialFolderCategory, "\uF599" },
            { WinoIconGlyph.SpecialFolderUnread, "\uF529" },
            { WinoIconGlyph.SpecialFolderForums, "\uF5B8" },
            { WinoIconGlyph.SpecialFolderUpdated, "\uF565" },
            { WinoIconGlyph.SpecialFolderPersonal, "\uE25A" },
            { WinoIconGlyph.SpecialFolderPromotions, "\uF7B6" },
            { WinoIconGlyph.SpecialFolderSocial, "\uEEEB" },
            { WinoIconGlyph.SpecialFolderOther, "\uE643" },
            { WinoIconGlyph.SpecialFolderMore, "\uF0F4" },
            { WinoIconGlyph.Microsoft, "\uE904" },
            { WinoIconGlyph.Google, "\uE905" },
            { WinoIconGlyph.NewMail, "\uF107" },
            { WinoIconGlyph.TurnOfNotifications, "\uF11D" },
            { WinoIconGlyph.Rename, "\uF668" },
            { WinoIconGlyph.EmptyFolder, "\uE47E" },
            { WinoIconGlyph.DontSync, "\uF195" },
            { WinoIconGlyph.Move, "\uE7B8" },
            { WinoIconGlyph.Mail, "\uF509" },
            { WinoIconGlyph.More, "\uE824" },
            { WinoIconGlyph.CustomServer, "\uF509" },
            { WinoIconGlyph.Print, "\uE922" },
            { WinoIconGlyph.Attachment, "\uE723" },
            { WinoIconGlyph.SortTextDesc, "\U000F3606" },
            { WinoIconGlyph.SortLinesDesc, "\U000F038A" },
            { WinoIconGlyph.Certificate, "\uEB95" },
            { WinoIconGlyph.OpenInNewWindow, "\uE8A7" },
            { WinoIconGlyph.Message, "\uE8BD" },
            { WinoIconGlyph.New, "\U000F002A" },
            { WinoIconGlyph.Blocked,"\uF140" },
            { WinoIconGlyph.IMAP, "\uE715" },
            { WinoIconGlyph.Calendar, "\uE912" },
            { WinoIconGlyph.CalendarToday, "\uE911" },
            { WinoIconGlyph.CalendarDay, "\uE913" },
            { WinoIconGlyph.CalendarWeek, "\uE914" },
            { WinoIconGlyph.CalendarMonth, "\uE91c" },
            { WinoIconGlyph.CalendarYear, "\uE917" },
            { WinoIconGlyph.WeatherBlow, "\uE907" },
            { WinoIconGlyph.WeatherCloudy, "\uE920" },
            { WinoIconGlyph.WeatherSunny, "\uE90e" },
            { WinoIconGlyph.WeatherRainy, "\uE908" },
            { WinoIconGlyph.WeatherSnowy, "\uE90a" },
            { WinoIconGlyph.WeatherSnowShowerAtNight, "\uE90c" },
            { WinoIconGlyph.WeatherThunderstorm, "\uE906" },
            { WinoIconGlyph.CalendarEventRepeat, "\uE915" },
            { WinoIconGlyph.CalendarEventMuiltiDay, "\uE91b" },
            { WinoIconGlyph.Reminder, "\uE918" },
            { WinoIconGlyph.CalendarAttendee, "\uE91a" },
            { WinoIconGlyph.CalendarSync, "\uE91d" },
            { WinoIconGlyph.CalendarError, "\uE916" },
            { WinoIconGlyph.CalendarAttendees, "\uE929" },
            { WinoIconGlyph.EventEditSeries, "\uE92A" },
            { WinoIconGlyph.EventTentative, "\uE928" },
            { WinoIconGlyph.EventAccept, "\uE925" },
            { WinoIconGlyph.EventRespond, "\uE924" },
            { WinoIconGlyph.EventReminder, "\uE923" },
            { WinoIconGlyph.EventJoinOnline, "\uE926" },
            { WinoIconGlyph.ViewMessageSource, "\uE943" },
            { WinoIconGlyph.Apple, "\uE92B" },
            { WinoIconGlyph.Yahoo, "\uE92C" }
        };
    }
}
