using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Wino.SourceGenerators.Rpc;

/// <summary>
/// Generates the deliberately small messenger bridge from the types explicitly listed on
/// CommunicationMessagesContext. Namespace direction is part of the contract:
/// UI and Client messages travel companion-to-UWP, Server messages travel UWP-to-companion.
/// </summary>
[Generator]
public sealed class RpcEventRegistryGenerator : IIncrementalGenerator
{
    private const string MessageContextMetadataName = "Wino.Messaging.CommunicationMessagesContext";
    private const string JsonSerializableAttributeName = "System.Text.Json.Serialization.JsonSerializableAttribute";

    private static readonly DiagnosticDescriptor DuplicateEventName = new(
        id: "WINORPC004",
        title: "Duplicate UI message type name",
        messageFormat: "Two IUIMessage types share the short name '{0}' ({1} and {2}). Event routing uses short names; rename one of them.",
        category: "WinoRpc",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(spc, compilation));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        if (compilation.AssemblyName != RpcModel.ContractsAssemblyName)
            return;

        var messageContext = compilation.GetTypeByMetadataName(MessageContextMetadataName);
        if (messageContext == null)
            return;

        var messageTypes = messageContext.GetAttributes()
            .Where(a => a.AttributeClass?.ToDisplayString() == JsonSerializableAttributeName
                        && a.ConstructorArguments.Length > 0)
            .Select(a => a.ConstructorArguments[0].Value as INamedTypeSymbol)
            .Where(t => t != null
                        && t.TypeKind == TypeKind.Class
                        && !t.IsAbstract
                        && !t.IsGenericType
                        && t.DeclaredAccessibility == Accessibility.Public
                        && t.ContainingNamespace.ToDisplayString().StartsWith("Wino.Messaging.", StringComparison.Ordinal))
            .Select(t => t!)
            .OrderBy(t => t.ToDisplayString(), StringComparer.Ordinal)
            .ToList();

        if (messageTypes.Count == 0)
            return;

        // Short names are the wire identifiers; enforce uniqueness.
        var byShortName = new Dictionary<string, INamedTypeSymbol>();
        foreach (var type in messageTypes)
        {
            if (byShortName.TryGetValue(type.Name, out var existing))
            {
                if (!SymbolEqualityComparer.Default.Equals(existing, type))
                {
                    context.ReportDiagnostic(Diagnostic.Create(DuplicateEventName, Location.None, type.Name, existing.ToDisplayString(), type.ToDisplayString()));
                }

                continue;
            }

            byShortName[type.Name] = type;
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated by Wino RpcEventRegistryGenerator />");
        builder.AppendLine("#nullable disable");
        builder.AppendLine($"namespace {RpcModel.GeneratedNamespace}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Bridges IUIMessage records across AppService.</summary>");
        builder.AppendLine("    public static class WinoRpcEventRegistry");
        builder.AppendLine("    {");

        var companionToUi = byShortName
            .Where(p => !p.Value.ContainingNamespace.ToDisplayString().StartsWith("Wino.Messaging.Server", StringComparison.Ordinal))
            .OrderBy(p => p.Key, StringComparer.Ordinal)
            .ToList();
        var uiToCompanion = byShortName
            .Where(p => p.Value.ContainingNamespace.ToDisplayString().StartsWith("Wino.Messaging.Server", StringComparison.Ordinal))
            .OrderBy(p => p.Key, StringComparer.Ordinal)
            .ToList();

        builder.AppendLine("        /// <summary>Registers only explicitly approved companion-to-UI events.</summary>");
        builder.AppendLine("        public static void RegisterCompanionToUi(global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, global::Wino.AppServices.Contracts.IWinoRpcEventSink sink)");
        builder.AppendLine("        {");

        foreach (var pair in companionToUi)
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"            global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Register<{display}>(messenger, sink, static (recipient, message) => ((global::Wino.AppServices.Contracts.IWinoRpcEventSink)recipient).Publish(message));");
        }

        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static void Unregister(global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, global::Wino.AppServices.Contracts.IWinoRpcEventSink sink)");
        builder.AppendLine("            => messenger.UnregisterAll(sink);");
        builder.AppendLine();

        // Companion side: object -> (typeName, utf8 payload).
        builder.AppendLine("        /// <summary>Serializes a UI message for forwarding. Returns false for unknown types.</summary>");
        builder.AppendLine("        public static bool TrySerializeCompanionToUi(object message, out string typeName, out byte[] payloadUtf8Json)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (message)");
        builder.AppendLine("            {");

        foreach (var pair in companionToUi)
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case {display} typedMessage:");
            builder.AppendLine($"                    typeName = \"ui.{pair.Key}.v1\";");
            builder.AppendLine($"                    payloadUtf8Json = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(typedMessage, global::Wino.Messaging.CommunicationMessagesContext.Default.GetTypeInfo(typeof({display}))!);");
            builder.AppendLine("                    return true;");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    typeName = null;");
        builder.AppendLine("                    payloadUtf8Json = null;");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();

        // UI side: (typeName, payload) -> typed messenger publication.
        builder.AppendLine("        /// <summary>Deserializes a forwarded UI message and publishes it into the given messenger. Returns false for unknown types.</summary>");
        builder.AppendLine("        public static bool TryPublishCompanionToUi(string typeName, global::System.Text.Json.JsonElement payload, global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (typeName)");
        builder.AppendLine("            {");

        foreach (var pair in companionToUi)
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case \"ui.{pair.Key}.v1\":");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var message = ({display})global::System.Text.Json.JsonSerializer.Deserialize(payload, global::Wino.Messaging.CommunicationMessagesContext.Default.GetTypeInfo(typeof({display}))!)!;");
            builder.AppendLine("                    if (message != null) global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send(messenger, message);");
            builder.AppendLine("                    return true;");
            builder.AppendLine("                }");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TrySerializeUiToCompanion(object message, out string typeName, out byte[] payloadUtf8Json)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (message)");
        builder.AppendLine("            {");
        foreach (var pair in uiToCompanion)
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case {display} typedMessage:");
            builder.AppendLine($"                    typeName = \"server.{pair.Key}.v1\";");
            builder.AppendLine($"                    payloadUtf8Json = global::System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(typedMessage, global::Wino.Messaging.CommunicationMessagesContext.Default.GetTypeInfo(typeof({display}))!);");
            builder.AppendLine("                    return true;");
        }
        builder.AppendLine("                default:");
        builder.AppendLine("                    typeName = null;");
        builder.AppendLine("                    payloadUtf8Json = null;");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public static bool TryPublishUiToCompanion(string typeName, global::System.Text.Json.JsonElement payload, global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (typeName)");
        builder.AppendLine("            {");
        foreach (var pair in uiToCompanion)
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case \"server.{pair.Key}.v1\":");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var message = ({display})global::System.Text.Json.JsonSerializer.Deserialize(payload, global::Wino.Messaging.CommunicationMessagesContext.Default.GetTypeInfo(typeof({display}))!)!;");
            builder.AppendLine("                    if (message != null) global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send(messenger, message);");
            builder.AppendLine("                    return true;");
            builder.AppendLine("                }");
        }
        builder.AppendLine("                default:");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("WinoRpcEventRegistry.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
