using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Wino.SourceGenerators.Rpc;

/// <summary>
/// Generates, inside Wino.Ipc.Contracts, the registry that bridges IUIMessage records
/// across the pipe: serialization on the companion side and typed re-publication into
/// the local messenger on the UI side. Supersedes the manually maintained
/// CommunicationMessagesContext list.
/// </summary>
[Generator]
public sealed class RpcEventRegistryGenerator : IIncrementalGenerator
{
    private const string UIMessageInterfaceName = "Wino.Core.Domain.Interfaces.IUIMessage";

    private static readonly DiagnosticDescriptor DuplicateEventName = new(
        id: "WINORPC004",
        title: "Duplicate UI message type name",
        messageFormat: "Two IUIMessage types share the short name '{0}' ({1} and {2}). Event routing uses short names; rename one of them.",
        category: "WinoRpc",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(spc, compilation));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        if (compilation.AssemblyName != RpcModel.ContractsAssemblyName)
            return;

        var messageTypes = RpcModel.GetAllWinoTypes(compilation)
            .Where(t => t.TypeKind == TypeKind.Class
                        && !t.IsAbstract
                        && !t.IsGenericType
                        && t.DeclaredAccessibility == Accessibility.Public
                        && t.AllInterfaces.Any(i => i.ToDisplayString() == UIMessageInterfaceName))
            .OrderBy(t => t.ToDisplayString(), StringComparer.Ordinal)
            .ToList();

        if (messageTypes.Count == 0)
            return;

        // Short names are the wire identifiers; enforce uniqueness.
        var byShortName = new Dictionary<string, INamedTypeSymbol>();
        foreach (var type in messageTypes)
        {
            if (byShortName.TryGetValue(type.Name, out var existing))
            {
                if (!SymbolEqualityComparer.Default.Equals(existing, type))
                {
                    context.ReportDiagnostic(Diagnostic.Create(DuplicateEventName, Location.None, type.Name, existing.ToDisplayString(), type.ToDisplayString()));
                }

                continue;
            }

            byShortName[type.Name] = type;
        }

        var builder = new StringBuilder();

        builder.AppendLine("// <auto-generated by Wino RpcEventRegistryGenerator />");
        builder.AppendLine("#nullable disable");
        builder.AppendLine($"namespace {RpcModel.GeneratedNamespace}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Bridges IUIMessage records across the IPC pipe.</summary>");
        builder.AppendLine("    public static class WinoRpcEventRegistry");
        builder.AppendLine("    {");

        // Companion side: object -> (typeName, utf8 payload).
        builder.AppendLine("        /// <summary>Serializes a UI message for forwarding. Returns false for unknown types.</summary>");
        builder.AppendLine("        public static bool TrySerialize(object message, out string typeName, out byte[] payloadUtf8Json)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (message)");
        builder.AppendLine("            {");

        foreach (var pair in byShortName.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case {display} typedMessage:");
            builder.AppendLine($"                    typeName = \"{pair.Key}\";");
            builder.AppendLine("                    payloadUtf8Json = global::Wino.Ipc.Contracts.WinoIpcJson.SerializeToUtf8Bytes(typedMessage);");
            builder.AppendLine("                    return true;");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    typeName = null;");
        builder.AppendLine("                    payloadUtf8Json = null;");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();

        // UI side: (typeName, payload) -> typed messenger publication.
        builder.AppendLine("        /// <summary>Deserializes a forwarded UI message and publishes it into the given messenger. Returns false for unknown types.</summary>");
        builder.AppendLine("        public static bool TryPublishToMessenger(string typeName, global::System.Text.Json.JsonElement payload, global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (typeName)");
        builder.AppendLine("            {");

        foreach (var pair in byShortName.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            var display = pair.Value.ToDisplayString(RpcModel.FullyQualified);
            builder.AppendLine($"                case \"{pair.Key}\":");
            builder.AppendLine("                {");
            builder.AppendLine($"                    var message = global::Wino.Ipc.Contracts.WinoIpcJson.Deserialize<{display}>(payload);");
            builder.AppendLine("                    if (message != null) global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.Send(messenger, message);");
            builder.AppendLine("                    return true;");
            builder.AppendLine("                }");
        }

        builder.AppendLine("                default:");
        builder.AppendLine("                    return false;");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        context.AddSource("WinoRpcEventRegistry.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
    }
}
