namespace Wino.Core.Domain.Enums;

/// <summary>
/// All registered views.
/// </summary>
public enum WinoPage
{
    None,
    IdlePage,
    ComposePage,
    SettingsPage,
    ContactsPage,
    MailRenderingPage,
    AccountDetailsPage,
    FolderCustomizationPage,
    MergedAccountDetailsPage,
    ManageAccountsPage,
    AccountManagementPage,
    SignatureManagementPage,
    AboutPage,
    PersonalizationPage,
    MessageListPage,
    MailNotificationSettingsPage,
    MailListPage,
    ReadComposePanePage,
    AppPreferencesPage,
    SettingOptionsPage,
    AliasManagementPage,
    MailCategoryManagementPage,
    ImapCalDavSettingsPage,
    KeyboardShortcutsPage,
    CalendarPage,
    CalendarSettingsPage,
    CalendarRenderingSettingsPage,
    CalendarNotificationSettingsPage,
    CalendarPreferenceSettingsPage,
    CalendarAccountSettingsPage,
    EventDetailsPage,
    CalendarEventComposePage,
    SignatureAndEncryptionPage,
    EmailTemplatesPage,
    CreateEmailTemplatePage,
    StoragePage,
    WinoAccountManagementPage,
    WelcomePageV2,
    WelcomeHostPage,
    ProviderSelectionPage,
    AccountSetupProgressPage,
    SpecialImapCredentialsPage
}
