namespace Wino.Core.Domain.Enums;

/// <summary>
/// All registered views.
/// </summary>
public enum WinoPage
{
    None,
    IdlePage,
    ComposePage,
    SettingsPage,
    ContactsPage,
    ContactEditPage,
    ToDoPage,
    MailRenderingPage,
    AccountDetailsPage,
    FolderCustomizationPage,
    MergedAccountDetailsPage,
    ManageAccountsPage,
    AccountManagementPage,
    SignatureManagementPage,
    AboutPage,
    PersonalizationPage,
    ApplicationThemeGalleryPage,
    ApplicationThemeEditorPage,
    MessageListPage,
    MailNotificationSettingsPage,
    UnreadBadgeSettingsPage,
    AccountUnreadBadgePage,
    MailListPage,
    ReadComposePanePage,
    AppPreferencesPage,
    MailPreferencesPage,
    BackupRestorePage,
    SettingOptionsPage,
    AliasManagementPage,
    MailCategoryManagementPage,
    MailFiltersPage,
    MailFilterEditorPage,
    ImapCalDavSettingsPage,
    KeyboardShortcutsPage,
    CalendarPage,
    CalendarSettingsPage,
    CalendarRenderingSettingsPage,
    CalendarNotificationSettingsPage,
    CalendarPreferenceSettingsPage,
    CalendarAccountSettingsPage,
    ContactsPreferenceSettingsPage,
    ToDoPreferenceSettingsPage,
    EventDetailsPage,
    CalendarEventComposePage,
    SignatureAndEncryptionPage,
    EmailTemplatesPage,
    CreateEmailTemplatePage,
    StoragePage,
    WinoAccountManagementPage,
    WinoIntelligencePage,
    WelcomePageV2,
    WelcomeHostPage,
    ProviderSelectionPage,
    AccountSetupProgressPage,
    SpecialImapCredentialsPage,
    TestPage,
    WinoIntelligenceManagementPage,
    IntelligenceCoveragePage
}
