using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Wino.SourceGenerators.Preferences;

/// <summary>
/// Generates the strongly typed preference accessor table used by PreferencesService.
/// This removes PropertyInfo/GetValue/SetValue from settings import and export so the
/// feature remains functional when reflection metadata is trimmed by Native AOT.
/// </summary>
[Generator]
public sealed class PreferencesPropertyGenerator : IIncrementalGenerator
{
    private const string InterfaceMetadataName = "Wino.Core.Domain.Interfaces.IPreferencesService";
    private const string ServiceMetadataName = "Wino.Mail.WinUI.Services.PreferencesService";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var model = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var preferenceInterface = compilation.GetTypeByMetadataName(InterfaceMetadataName);
            var preferenceService = compilation.GetTypeByMetadataName(ServiceMetadataName);

            if (preferenceInterface == null || preferenceService == null)
            {
                return ImmutableArray<IPropertySymbol>.Empty;
            }

            return preferenceInterface
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property =>
                    !property.IsIndexer &&
                    property.GetMethod != null &&
                    property.SetMethod != null &&
                    property.Name != "DiagnosticId")
                .OrderBy(static property => property.Name, StringComparer.Ordinal)
                .ToImmutableArray();
        });

        context.RegisterSourceOutput(model, static (sourceContext, properties) =>
        {
            if (properties.IsDefaultOrEmpty)
            {
                return;
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.AppendLine("namespace Wino.Mail.WinUI.Services;");
            source.AppendLine();
            source.AppendLine("public partial class PreferencesService");
            source.AppendLine("{");
            source.AppendLine("    private static partial PreferenceAccessor[] GetGeneratedSyncablePreferenceProperties() =>");
            source.AppendLine("        new PreferenceAccessor[]");
            source.AppendLine("        {");

            foreach (var property in properties)
            {
                var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append("            new(\"")
                    .Append(property.Name)
                    .Append("\", typeof(")
                    .Append(typeName)
                    .Append("), static service => service.")
                    .Append(property.Name)
                    .Append(", static (service, value) => service.")
                    .Append(property.Name)
                    .Append(" = (")
                    .Append(typeName)
                    .AppendLine(")value!),");
            }

            source.AppendLine("        };");
            source.AppendLine("}");

            sourceContext.AddSource("PreferencesService.Accessors.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }
}
