using System.Text.Json;
using System.Text.Json.Serialization;
using System.Text.Json.Serialization.Metadata;

namespace Wino.AppServices.Contracts;

/// <summary>
/// JSON metadata used by generated backend proxies. AOT is deliberately disabled for
/// the reverse migration, so domain DTO metadata can be resolved safely at runtime;
/// the outer AppService protocol remains source-generated by
/// <see cref="WinoAppServiceJsonContext"/>.
/// </summary>
public static class WinoRpcJson
{
    private static readonly JsonSerializerOptions Options = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        TypeInfoResolver = new DefaultJsonTypeInfoResolver(),
    };

    public static JsonTypeInfo<T> GetTypeInfo<T>() =>
        (JsonTypeInfo<T>)Options.GetTypeInfo(typeof(T));

    public static T Deserialize<T>(JsonElement payload) =>
        JsonSerializer.Deserialize(payload, GetTypeInfo<T>())
        ?? throw new JsonException($"RPC payload for {typeof(T).FullName} was null.");

    public static byte[] SerializeToUtf8Bytes<T>(T value) =>
        JsonSerializer.SerializeToUtf8Bytes(value, GetTypeInfo<T>());
}
