using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Wino.SourceGenerators.Icons;

/// <summary>
/// Generates code from icons/manifest.json, the single source of truth for the Wino icon fonts
/// (see icons/README.md).
/// <para>
/// By default it emits the WinoIconGlyph enum and its glyph lookup (Wino.Core.Domain). A project that
/// cannot reference Wino.Core.Domain, such as the reusable controls library, sets the MSBuild property
/// WinoIconCodesNamespace instead and gets a WinoIconCodes class of string constants in that namespace.
/// </para>
/// </summary>
[Generator]
public class WinoIconGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidManifest = new(
        id: "WINOICON001",
        title: "Invalid icon manifest",
        messageFormat: "icons/manifest.json could not be read: {0}",
        category: "WinoIcons",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var manifest = context.AdditionalTextsProvider
            .Where(static file => file.Path.Replace("\\", "/").EndsWith("icons/manifest.json", StringComparison.OrdinalIgnoreCase))
            .Select(static (file, cancellationToken) => file.GetText(cancellationToken)?.ToString())
            .WithTrackingName("WinoIconManifest");

        var codesNamespace = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) => options.GlobalOptions.TryGetValue("build_property.WinoIconCodesNamespace", out var value) && !string.IsNullOrWhiteSpace(value) ? value : null);

        context.RegisterSourceOutput(manifest.Combine(codesNamespace), static (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private static void Execute(string? json, string? codesNamespace, SourceProductionContext context)
    {
        if (string.IsNullOrWhiteSpace(json)) return;

        List<(string Name, string Glyph, string? AliasOf)> members;
        try
        {
            members = ReadMembers(json!);
        }
        catch (Exception ex) when (ex is JsonException or FormatException or KeyNotFoundException or InvalidOperationException)
        {
            context.ReportDiagnostic(Diagnostic.Create(InvalidManifest, Location.None, ex.Message));
            return;
        }

        if (codesNamespace != null)
        {
            context.AddSource("WinoIconCodes.g.cs", SourceText.From(BuildCodes(members, codesNamespace), Encoding.UTF8));
            return;
        }

        var enumBuilder = new StringBuilder();
        enumBuilder.AppendLine("// <auto-generated/> from icons/manifest.json. Do not edit; run icons/tools/add_fluent_icon.py instead.");
        enumBuilder.AppendLine("namespace Wino.Core.Domain.Enums");
        enumBuilder.AppendLine("{");
        enumBuilder.AppendLine("    /// <summary>Icons in the WinoIcons fonts. Generated from icons/manifest.json.</summary>");
        enumBuilder.AppendLine("    public enum WinoIconGlyph");
        enumBuilder.AppendLine("    {");
        enumBuilder.AppendLine("        None,");
        foreach (var (name, _, aliasOf) in members)
        {
            if (aliasOf != null)
                enumBuilder.AppendLine($"        /// <summary>Same glyph as <see cref=\"{aliasOf}\"/>.</summary>");
            enumBuilder.AppendLine($"        {name},");
        }
        enumBuilder.AppendLine("    }");
        enumBuilder.AppendLine("}");

        var mapBuilder = new StringBuilder();
        mapBuilder.AppendLine("// <auto-generated/> from icons/manifest.json.");
        mapBuilder.AppendLine("using Wino.Core.Domain.Enums;");
        mapBuilder.AppendLine();
        mapBuilder.AppendLine("namespace Wino.Core.Domain");
        mapBuilder.AppendLine("{");
        mapBuilder.AppendLine("    public static class WinoIconGlyphs");
        mapBuilder.AppendLine("    {");
        mapBuilder.AppendLine("        /// <summary>Returns the character for <paramref name=\"icon\"/> in the WinoIcons fonts.</summary>");
        mapBuilder.AppendLine("        public static string GetGlyph(WinoIconGlyph icon) => icon switch");
        mapBuilder.AppendLine("        {");
        foreach (var (name, glyph, _) in members)
        {
            mapBuilder.AppendLine($"            WinoIconGlyph.{name} => \"{glyph}\",");
        }
        mapBuilder.AppendLine("            _ => \" \",");
        mapBuilder.AppendLine("        };");
        mapBuilder.AppendLine("    }");
        mapBuilder.AppendLine("}");

        context.AddSource("WinoIconGlyph.g.cs", SourceText.From(enumBuilder.ToString(), Encoding.UTF8));
        context.AddSource("WinoIconGlyphs.g.cs", SourceText.From(mapBuilder.ToString(), Encoding.UTF8));
    }

    private static string BuildCodes(List<(string Name, string Glyph, string? AliasOf)> members, string codesNamespace)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/> from icons/manifest.json. Do not edit; run icons/tools/add_fluent_icon.py instead.");
        builder.AppendLine($"namespace {codesNamespace}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>Characters of the WinoIcons font, by icon name. Generated from icons/manifest.json.</summary>");
        builder.AppendLine("    public static class WinoIconCodes");
        builder.AppendLine("    {");
        foreach (var (name, glyph, _) in members)
        {
            builder.AppendLine($"        public const string {name} = \"{glyph}\";");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static List<(string Name, string Glyph, string? AliasOf)> ReadMembers(string json)
    {
        var members = new List<(string, string, string?)>();
        using var document = JsonDocument.Parse(json);

        foreach (var icon in document.RootElement.GetProperty("icons").EnumerateArray())
        {
            var name = icon.GetProperty("name").GetString() ?? throw new FormatException("icon without a name");
            var codepoint = int.Parse(icon.GetProperty("codepoint").GetString()!, NumberStyles.HexNumber, CultureInfo.InvariantCulture);
            var glyph = EscapeCodepoint(codepoint);

            members.Add((name, glyph, null));

            if (icon.TryGetProperty("aliases", out var aliases))
            {
                foreach (var alias in aliases.EnumerateArray())
                {
                    members.Add((alias.GetString()!, glyph, name));
                }
            }
        }

        var duplicate = members.GroupBy(m => m.Item1).FirstOrDefault(g => g.Count() > 1);
        if (duplicate != null) throw new FormatException($"duplicate icon name '{duplicate.Key}'");

        return members;
    }

    private static string EscapeCodepoint(int codepoint)
        => codepoint > 0xFFFF
            ? $"\\U{codepoint:X8}"
            : $"\\u{codepoint:X4}";
}
